
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ProgressBar progressbar3;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ProgressBar progressbar4;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.ProgressBar progressbar2;
	
	private global::Gtk.CheckButton checkbutton1;
	
	private global::Gtk.CheckButton checkbutton2;
	
	private global::Gtk.CheckButton checkbutton3;
	
	private global::Gtk.CheckButton checkbutton4;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("AGC");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 13;
		w1.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar3 = new global::Gtk.ProgressBar ();
		this.progressbar3.Name = "progressbar3";
		this.fixed1.Add (this.progressbar3);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar3]));
		w2.X = 12;
		w2.Y = 31;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Magnitude");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w3.X = 12;
		w3.Y = 60;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar4 = new global::Gtk.ProgressBar ();
		this.progressbar4.Name = "progressbar4";
		this.fixed1.Add (this.progressbar4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar4]));
		w4.X = 9;
		w4.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Angle");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w5.X = 14;
		w5.Y = 109;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progressbar2 = new global::Gtk.ProgressBar ();
		this.progressbar2.Name = "progressbar2";
		this.fixed1.Add (this.progressbar2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.progressbar2]));
		w6.X = 10;
		w6.Y = 129;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("COMP low (field high)");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed1.Add (this.checkbutton1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
		w7.X = 196;
		w7.Y = 26;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("COMP high (field low)");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed1.Add (this.checkbutton2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton2]));
		w8.X = 189;
		w8.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton3 = new global::Gtk.CheckButton ();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("COF (CORDIC overflow)");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.fixed1.Add (this.checkbutton3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton3]));
		w9.X = 184;
		w9.Y = 95;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton4 = new global::Gtk.CheckButton ();
		this.checkbutton4.Sensitive = false;
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("OCF (offset comp. finalised)");
		this.checkbutton4.Active = true;
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.fixed1.Add (this.checkbutton4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton4]));
		w10.X = 181;
		w10.Y = 131;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
